# Generated by Django 5.0.14 on 2026-06-11 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('skill', models.CharField(choices=[('mason', 'Mason (Kadiya)'), ('carpenter', 'Carpenter (Suthar)'), ('plumber', 'Plumber'), ('electrician', 'Electrician'), ('painter', 'Painter'), ('welder', 'Welder'), ('laborer', 'Helper / General Labor')], max_length=30)),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('location', models.CharField(choices=[('vastrapur', 'Vastrapur, Ahmedabad'), ('satellite', 'Satellite, Ahmedabad'), ('bopal', 'Bopal, Ahmedabad'), ('gota', 'Gota, Ahmedabad'), ('nikol', 'Nikol, Ahmedabad'), ('maninagar', 'Maninagar, Ahmedabad'), ('paldi', 'Paldi, Ahmedabad'), ('chandkheda', 'Chandkheda, Ahmedabad'), ('ranip', 'Ranip, Ahmedabad'), ('naranpura', 'Naranpura, Ahmedabad')], max_length=50)),
                ('availability', models.CharField(choices=[('available', 'Available Today'), ('busy', 'Busy'), ('soon', 'Available Soon')], default='available', max_length=20)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Daily rate in INR (optional)', max_digits=8, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='workers/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.workerprofile')),
            ],
        ),
    ]
