# Generated by Django 6.0.6 on 2026-06-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='location',
            field=models.CharField(choices=[('bopal_ahmedabad', 'Bopal (Ahmedabad)'), ('satellite_ahmedabad', 'Satellite (Ahmedabad)'), ('vastrapur_ahmedabad', 'Vastrapur (Ahmedabad)'), ('naroda_ahmedabad', 'Naroda (Ahmedabad)'), ('gondal_chowkdi_rajkot', 'Gondal Chowkdi (Rajkot)'), ('bus_stand_rajkot', 'Bus Stand (Rajkot)'), ('indira_circle_rajkot', 'Indira Circle (Rajkot)'), ('kalawad_road_rajkot', 'Kalawad Road (Rajkot)'), ('chhaya_porbandar', 'Chhaya (Porbandar)'), ('sudama_puri_porbandar', 'Sudama Puri (Porbandar)'), ('khapat_porbandar', 'Khapat (Porbandar)'), ('kamla_bagh_porbandar', 'Kamla Bagh (Porbandar)'), ('kaliyabid_bhavnagar', 'Kaliyabid (Bhavnagar)'), ('ghogha_circle_bhavnagar', 'Ghogha Circle (Bhavnagar)'), ('chitra_bhavnagar', 'Chitra (Bhavnagar)'), ('subhashnagar_bhavnagar', 'Subhashnagar (Bhavnagar)')], max_length=50),
        ),
    ]
